language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install: |
  virtualenv .venv
  source .venv/bin/activate
  pip install -e .
  pip install -r test-requirements.txt
script: |
  source .venv/bin/activate
  NUM_RANDOM_CALLS=200 py.test
